eval_setting:
  split:
    RS: [0.8, 0.1, 0.1]
  order: RO
  group_by: user
  mode: full

train_batch_size: 256
eval_batch_size: 409600000

valid_metric: NDCG@10
metrics: ["Recall", "NDCG"]
topk: [10, 20, 50]

save_dataset: True

n_layers: 3
reg_weight: 0.0001

epochs: 1000
learning_rate: 0.001
stopping_step: 5
embedding_size: 64

